import { NextResponse } from 'next/server'
import { supabase } from '@/lib/supabase'

// DEMO ONLY — delete this file after seeding

const leads = [
  {
    phone: '+4915112345678',
    full_name: 'Hans Müller',
    email: 'hans.mueller@gmx.de',
    car_make: 'BMW',
    car_model: '5er Reihe',
    car_year: '2019',
    mileage: '87000',
    asking_price: '28500',
    previous_owners: '1',
    condition: 'Sehr gepflegt, alle Serviceheft vorhanden. Kleiner Kratzer am hinteren Stoßfänger.',
    status: 'new',
    email_sent_at: null,
    created_at: daysAgo(1),
  },
  {
    phone: '+4917612345679',
    full_name: 'Klaus Weber',
    email: 'k.weber@t-online.de',
    car_make: 'Mercedes-Benz',
    car_model: 'E-Klasse',
    car_year: '2020',
    mileage: '54000',
    asking_price: '41000',
    previous_owners: '1',
    condition: 'Unfallfreies Fahrzeug, Nichtraucher, Sitzheizung und Panoramadach.',
    status: 'new',
    email_sent_at: null,
    created_at: daysAgo(1),
  },
  {
    phone: '+4916312345680',
    full_name: 'Thomas Schneider',
    email: 'thomas.schneider@web.de',
    car_make: 'Audi',
    car_model: 'A6',
    car_year: '2018',
    mileage: '112000',
    asking_price: '22000',
    previous_owners: '2',
    condition: 'New tyres fitted last month, full service history. Minor scratch on rear door.',
    status: 'contacted',
    email_sent_at: daysAgo(0),
    created_at: daysAgo(2),
  },
  {
    phone: '+4915212345681',
    full_name: 'Michael Fischer',
    email: 'mfischer@gmail.com',
    car_make: 'Volkswagen',
    car_model: 'Tiguan',
    car_year: '2021',
    mileage: '38000',
    asking_price: '33500',
    previous_owners: '1',
    condition: 'Wie neu, kein Unfall, Garantie bis 2024 noch vorhanden.',
    status: 'new',
    email_sent_at: null,
    created_at: daysAgo(1),
  },
  {
    phone: '+4917212345682',
    full_name: 'Andreas Meyer',
    email: 'a.meyer@freenet.de',
    car_make: 'Porsche',
    car_model: 'Cayenne',
    car_year: '2017',
    mileage: '95000',
    asking_price: '52000',
    previous_owners: '2',
    condition: 'Sport Chrono Paket, Luftfederung, Panoramadach. Gepflegter Zustand.',
    status: 'contacted',
    email_sent_at: daysAgo(0),
    created_at: daysAgo(3),
  },
  {
    phone: '+4916012345683',
    full_name: 'Stefan Wagner',
    email: 'stefan.wagner@gmx.de',
    car_make: 'BMW',
    car_model: 'X5',
    car_year: '2020',
    mileage: '61000',
    asking_price: '58000',
    previous_owners: '1',
    condition: null,
    status: 'new',
    email_sent_at: null,
    created_at: daysAgo(0),
  },
  {
    phone: '+4915312345684',
    full_name: 'Peter Becker',
    email: 'peter.becker@yahoo.de',
    car_make: 'Audi',
    car_model: 'Q5',
    car_year: '2019',
    mileage: '74000',
    asking_price: '31000',
    previous_owners: '1',
    condition: 'S-Line Paket, Matrix LED, Virtual Cockpit. Scheckheftgepflegt.',
    status: 'closed',
    email_sent_at: daysAgo(5),
    created_at: daysAgo(7),
  },
  {
    phone: '+4917012345685',
    full_name: 'Markus Schulz',
    email: 'markus.schulz@t-online.de',
    car_make: 'Mercedes-Benz',
    car_model: 'GLC 300',
    car_year: '2021',
    mileage: '29000',
    asking_price: '47500',
    previous_owners: '1',
    condition: 'One owner from new. Full AMG Line spec. Minor kerb scuff on rear alloy.',
    status: 'new',
    email_sent_at: null,
    created_at: daysAgo(1),
  },
  {
    phone: '+4915712345686',
    full_name: 'Jürgen Koch',
    email: 'j.koch@web.de',
    car_make: 'Volkswagen',
    car_model: 'Golf GTI',
    car_year: '2022',
    mileage: '18000',
    asking_price: '34000',
    previous_owners: '1',
    condition: null,
    status: 'contacted',
    email_sent_at: daysAgo(1),
    created_at: daysAgo(2),
  },
  {
    phone: '+4916212345687',
    full_name: 'Christian Bauer',
    email: 'christian.bauer@gmx.de',
    car_make: 'BMW',
    car_model: '3er Touring',
    car_year: '2018',
    mileage: '128000',
    asking_price: '18500',
    previous_owners: '2',
    condition: 'Klimaanlage kürzlich gewartet. Neue Bremsscheiben vorne. Guter Allgemeinzustand.',
    status: 'closed',
    email_sent_at: daysAgo(6),
    created_at: daysAgo(8),
  },
  {
    phone: '+4917512345688',
    full_name: 'Rainer Hoffmann',
    email: 'r.hoffmann@freenet.de',
    car_make: 'Audi',
    car_model: 'A4 Avant',
    car_year: '2020',
    mileage: '48000',
    asking_price: '29000',
    previous_owners: '1',
    condition: 'Quattro Allrad, S-Tronic, LED Matrix. Gepflegter Nichtraucherzustand.',
    status: 'new',
    email_sent_at: null,
    created_at: daysAgo(0),
  },
  {
    phone: '+4915512345689',
    full_name: 'Dieter Richter',
    email: 'dieter.richter@t-online.de',
    car_make: 'Opel',
    car_model: 'Insignia',
    car_year: '2017',
    mileage: '143000',
    asking_price: '9500',
    previous_owners: '3',
    condition: 'Gebrauchsspuren vorhanden. Motor und Getriebe einwandfrei. TÜV neu.',
    status: 'new',
    email_sent_at: null,
    created_at: daysAgo(1),
  },
  {
    phone: '+4917312345690',
    full_name: 'Werner Klein',
    email: 'werner.klein@gmail.com',
    car_make: 'Mercedes-Benz',
    car_model: 'C-Klasse',
    car_year: '2019',
    mileage: '67000',
    asking_price: '26500',
    previous_owners: '1',
    condition: 'AMG Line Exterieur, Burmester Sound, Schiebedach. Sehr gepflegt.',
    status: 'contacted',
    email_sent_at: daysAgo(0),
    created_at: daysAgo(2),
  },
  {
    phone: '+4916512345691',
    full_name: 'Bernd Wolf',
    email: 'b.wolf@web.de',
    car_make: 'BMW',
    car_model: 'X3',
    car_year: '2021',
    mileage: '41000',
    asking_price: '44000',
    previous_owners: '1',
    condition: null,
    status: 'new',
    email_sent_at: null,
    created_at: daysAgo(0),
  },
  {
    phone: '+4915812345692',
    full_name: 'Uwe Schröder',
    email: 'uwe.schroeder@gmx.de',
    car_make: 'Ford',
    car_model: 'Mustang GT',
    car_year: '2018',
    mileage: '52000',
    asking_price: '35000',
    previous_owners: '1',
    condition: 'V8 5.0L, Fascia pack, performance exhaust. Imported from USA. All papers in order.',
    status: 'contacted',
    email_sent_at: daysAgo(1),
    created_at: daysAgo(3),
  },
  {
    phone: '+4917112345693',
    full_name: 'Helmut Braun',
    email: 'helmut.braun@yahoo.de',
    car_make: 'Volkswagen',
    car_model: 'Passat',
    car_year: '2020',
    mileage: '89000',
    asking_price: '21000',
    previous_owners: '1',
    condition: 'Firmenfahrzeug, regelmäßige Wartung beim VW-Händler. Sitzheizung, Navi.',
    status: 'new',
    email_sent_at: null,
    created_at: daysAgo(1),
  },
  {
    phone: '+4915412345694',
    full_name: 'Frank Zimmermann',
    email: 'frank.zimmermann@freenet.de',
    car_make: 'Audi',
    car_model: 'Q7',
    car_year: '2016',
    mileage: '178000',
    asking_price: '24000',
    previous_owners: '2',
    condition: 'Luftfederung funktioniert einwandfrei. 7-Sitzer, Panoramadach. HU neu.',
    status: 'closed',
    email_sent_at: daysAgo(4),
    created_at: daysAgo(6),
  },
  {
    phone: '+4916812345695',
    full_name: 'Holger Krause',
    email: 'h.krause@t-online.de',
    car_make: 'Mercedes-Benz',
    car_model: 'A-Klasse 200',
    car_year: '2022',
    mileage: '14000',
    asking_price: '29500',
    previous_owners: '1',
    condition: 'Fast neu, noch Werksgarantie vorhanden. Rückfahrkamera, Einparkhilfe.',
    status: 'new',
    email_sent_at: null,
    created_at: daysAgo(0),
  },
  {
    phone: '+4917812345696',
    full_name: 'Günter Neumann',
    email: 'guenter.neumann@gmx.de',
    car_make: 'BMW',
    car_model: '7er',
    car_year: '2017',
    mileage: '109000',
    asking_price: '38000',
    previous_owners: '2',
    condition: 'Executive Lounge, Softclose, Head-Up Display. Kleinere Gebrauchsspuren.',
    status: 'contacted',
    email_sent_at: daysAgo(0),
    created_at: daysAgo(2),
  },
  {
    phone: '+4916712345697',
    full_name: 'Karl-Heinz Hartmann',
    email: 'kh.hartmann@web.de',
    car_make: 'Porsche',
    car_model: '911 Carrera',
    car_year: '2015',
    mileage: '62000',
    asking_price: '72000',
    previous_owners: '1',
    condition: 'PDK, Sport Exhaust, Bose Sound. Lückenlose Servicedokumentation beim Porsche Zentrum.',
    status: 'closed',
    email_sent_at: daysAgo(3),
    created_at: daysAgo(5),
  },
]

function daysAgo(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  d.setHours(Math.floor(Math.random() * 12) + 8)
  d.setMinutes(Math.floor(Math.random() * 60))
  return d.toISOString()
}

export async function GET() {
  // First clear existing demo leads
  await supabase.from('leads').delete().like('phone', '+491%1234567%')

  const { data, error } = await supabase.from('leads').insert(leads).select()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json({
    message: `✓ ${data.length} demo leads inserted. Delete /app/api/seed/ when done.`,
    count: data.length,
  })
}
